█epoch     train_loss  valid_loss  sens      spec      dice      my_Dice_Loss  acc       time    
██0         0.028056    0.015723    0.923319  0.993884  0.958828  -3.338300     0.925672  07:03     
██1         0.019043    0.011949    0.936333  0.995095  0.966150  -3.364046     0.927754  03:26     
██2         0.015391    0.014410    0.937654  0.994801  0.965529  -3.413170     0.925875  03:26     
██3         0.014035    0.011468    0.945419  0.995565  0.970525  -3.393622     0.928542  03:25     
██4         0.013488    0.010616    0.950403  0.995926  0.973593  -3.322117     0.927156  03:26     
██5         0.018254    0.010837    0.951498  0.996238  0.974519  -3.345798     0.928320  03:26     
██6         0.010453    0.009260    0.955797  0.996463  0.976801  -3.296413     0.928059  03:26     
██7         0.009994    0.008305    0.956242  0.996598  0.976954  -3.309944     0.927709  03:26     
██8         0.011964    0.009933    0.950545  0.996061  0.973796  -3.306144     0.926295  03:26     
██9         0.011842    0.008029    0.955905  0.996616  0.976872  -3.273455     0.928555  03:26     
██10        0.012258    0.008238    0.956574  0.996577  0.976794  -3.291255     0.927678  03:27     
██11        0.009813    0.007254    0.959406  0.996892  0.978795  -3.304529     0.928008  03:26     
██12        0.015253    0.007838    0.955656  0.996694  0.976579  -3.275575     0.928985  03:26     
██13        0.013144    0.009198    0.953952  0.996307  0.975468  -3.334606     0.929001  03:26     
██14        0.007775    0.006317    0.963206  0.997222  0.980914  -3.250311     0.928119  03:26     
Traceback (most recent call last):
  File "pawsey/unet.py", line 82, in <module>
    MLPY.save_model(learner.model, run_dir+'/model')
  File "/opt/conda/lib/python3.7/site-packages/mlflow/pytorch/__init__.py", line 231, in save_model
    raise RuntimeError("Path '{}' already exists".format(path))
RuntimeError: Path '/workspace/oct_ca_seg/runsaves/UNET/model' already exists
srun: error: a082: task 0: Exited with exit code 1
